### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [TeamAmaze/AmazeFileUtilities#179]
Your recent update triggered some of the newer scanners at IzzyOnDroid (btw, no [IoD a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) in your Readme?):

```
! repo/com.amaze.fileutilities_136.apk declares sensitive permission(s):
  android.permission.READ_EXTERNAL_STORAGE android.permission.MANAGE_EXTERNAL_STORAGE
  android.permission.QUERY_ALL_PACKAGES android.permission.ACCESS_FINE_LOCATION
  android.permission.ACCESS_COARSE_LOCATION android.permission.REQUEST_DELETE_PACKAGES
  android.permission.READ_PHONE_STATE
! repo/com.amaze.fileutilities_136.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Checking with the latest app description, I could already clarify storage and `QUERY_ALL_PACKAGES`:

```yaml
android.permission.READ_EXTERNAL_STORAGE: needed for file management
android.permission.MANAGE_EXTERNAL_STORAGE: needed for file management on higher Android versions
android.permission.QUERY_ALL_PACKAGES: needed to show/group apps
```

Could you please clarify the others?

As for `DEPENDENCY_INFO_BLOCK`, that can easily be avoided with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!
